cluster:
  name: development
  domain: sandbox2417.opentlc.com
  fqdn: development.sandbox2417.opentlc.com
  address: "https://api.development.sandbox2417.opentlc.com:6443"
  environment: dev
  cloud: aws
  region: us-east-2
#  registry: quay-dev.io

infraConfig:
  include: true
  nodes:
  - ip-10-0-145-199.us-east-2.compute.internal
  - ip-10-0-158-8.us-east-2.compute.internal

#catalogSource:
#  rh_catalog_version: v4.10

#ingress:
#  controller:
#    syslog:
#      address: 10.9.0.1
