cluster:
  name: development
  domain: sandbox2417.opentlc.com
  fqdn: development.sandbox2417.opentlc.com
  address: "https://api.development.sandbox2417.opentlc.com:6443"
  environment: dev
  cloud: aws
  region: us-east-2
#  registry: quay-dev.io

infraConfig:
  include: true
  nodes:
  - ip-10-0-133-87.ec2.internal
  - ip-10-0-152-67.ec2.internal

consoleLogo:
  include: true
  logoConfigMapName: custom-logo
  logoImageFilepath: files/custom-logo-dha.png

clusterAutoscaler:
  include: true
  name: "default"
  podPriorityThreshold: -10
  resourceLimits:
    maxNodesTotal: 24
    cores:
      min: 8
      max: 128
    memory:
      min: 4
      max: 256
#    gpus:
#      - type: nvidia.com/gpu
#        min: 0
#        max: 16
#      - type: amd.com/gpu
#        min: 0
#        max: 4
  logVerbosity: 4
  scaleDown:
    enabled: true
    delayAfterAdd: 10m
    delayAfterDelete: 5m
    delayAfterFailure: 30s
    unneededTime: 5m
    utilizationThreshold: "0.4"

#catalogSource:
#  rh_catalog_version: v4.10

#ingress:
#  controller:
#    syslog:
#      address: 10.9.0.1
