{{- if .Values.consoleLogo.include }}

---
{{- $imageFile := .Values.consoleLogo.logoImageFilepath }}
{{- $imageContent := .Files.Get $imageFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.consoleLogo.logoConfigMapName }}
  namespace: openshift-config
binaryData:
  debug_imageFile: {{ $imageFile | quote }}
  debug_imageContent: {{ $imageContent | b64enc | quote }}

{{ end }}
