{{- if .Values.consoleLogo.include }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.consoleLogo.logoConfigMapName }}
  namespace: openshift-config
binaryData:
{{- $imageContent := .Files.Get "files/custom-logo.png" | b64enc | quote }}
debug_imageContent: {{ $imageContent }}

{{ end }}
