{{- if .Values.consoleLogo.include }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.consoleLogo.logoConfigMapName }}
  namespace: openshift-config
data:
  debug_currentWorkingDir: {{ $cwd | quote }}
{{- $imageContent := .Files.Get "files/custom-logo.png" | b64enc | quote }}
binaryData:
  debug_imageContent: {{ $imageContent }}

{{ end }}
