{{- if .Values.consoleLogo.include }}

---
{{- $imageFile := .Values.consoleLogo.logoImageFilepath }}
{{- $imageName := filepath.Base $imageFile }}
{{- $imageContent := .Files.Get $imageFile | b64enc | quote }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.consoleLogo.logoConfigMapName }}
  namespace: openshift-config
data:
  {{ $imageName }}: {{ $imageContent }}

{{ end }}
