{{- if .Values.consoleLogo.include }}

---
{{- $imageFile := .Values.consoleLogo.logoImageFilepath }}
{{- $imageContent := .Files.Get $imageFile | b64enc | quote }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.consoleLogo.logoConfigMapName }}
  namespace: openshift-config
data:
  debug_imageFile: {{ $imageFile | quote }}
  debug_imageContent: {{ $imageContent }}

{{ end }}
