{{- if .Values.consoleLogo.include }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.consoleLogo.logoConfigMapName }}
  namespace: openshift-config
binaryData:
{{- $imageFile := .Values.consoleLogo.logoImageFilepath }}
{{- $imageContent := .Files.Get $imageFile | b64enc | quote }}
debug_imageFile: {{ $imageFile | quote }}
debug_imageContent: {{ $imageContent }}

{{ end }}
